[2024-06-11T06:46:24.292+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-11T06:46:24.307+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mssql_to_postgresql_13.load_to_postgresql scheduled__2024-06-10T00:00:00+00:00 [queued]>
[2024-06-11T06:46:24.310+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mssql_to_postgresql_13.load_to_postgresql scheduled__2024-06-10T00:00:00+00:00 [queued]>
[2024-06-11T06:46:24.311+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-11T06:46:24.316+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_to_postgresql> on 2024-06-10 00:00:00+00:00
[2024-06-11T06:46:24.320+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'mssql_to_postgresql_13', 'load_to_postgresql', 'scheduled__2024-06-10T00:00:00+00:00', '--job-id', '47', '--raw', '--subdir', 'DAGS_FOLDER/copy_file_transfer.py', '--cfg-path', '/tmp/tmp5zs4whpw']
[2024-06-11T06:46:24.322+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=3364) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-11T06:46:24.323+0000] {standard_task_runner.py:91} INFO - Job 47: Subtask load_to_postgresql
[2024-06-11T06:46:24.323+0000] {standard_task_runner.py:63} INFO - Started process 3366 to run task
[2024-06-11T06:46:24.346+0000] {task_command.py:426} INFO - Running <TaskInstance: mssql_to_postgresql_13.load_to_postgresql scheduled__2024-06-10T00:00:00+00:00 [running]> on host 2e5c63130483
[2024-06-11T06:46:24.383+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='mssql_to_postgresql_13' AIRFLOW_CTX_TASK_ID='load_to_postgresql' AIRFLOW_CTX_EXECUTION_DATE='2024-06-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-10T00:00:00+00:00'
[2024-06-11T06:46:24.383+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-11T06:46:24.398+0000] {base.py:84} INFO - Using connection ID 'postgres_conn' for task execution.
[2024-06-11T06:46:24.402+0000] {sql.py:470} INFO - Running statement: 
    INSERT INTO raw_data.cybertrack_superapps_v_transfer (
        "Id", 
        "TransactionID", 
        "TransactionDatetime", 
        "TransactionType", 
        "TransactionAmount", 
        "TransactionStatus", 
        "SourceAccountId", 
        "SourceAccountName", 
        "SourceAccountType", 
        "DestinationAccountId", 
        "DestinationAccountName", 
        "DestinationAccountBank", 
        "TransactionCategory", 
        "AccountCIFNo", 
        "AccountPhoneNo", 
        "AccountEmail", 
        "SourceAccountStatus",
        "TimeGetData"
    ) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
    , parameters: [1023441, 'TB2024061078062253', datetime.datetime(2024, 6, 10, 22, 48, 38, 970000), 'TRF_BIFAST', 107500, 'Success', '619e5479cbe178e81b36ddc98b3018be', '5c9516baef42d316a891a276633e491d', 'SAVING', '693817191564', 'OKTAVIANUS DWI FIGO NAINGGOLAN', 'OCBC', 'TRF_BIFAST', '240603140111000', 'edd46da3a52880334c0f2795f5e5344f', '9ea5955fd9a9bb7621e5398b0459c9d5', 'ACTIVE', '2024-06-11 06:46:23']
[2024-06-11T06:46:24.403+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-11T06:46:24.404+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/copy_file_transfer.py", line 62, in load_to_postgresql
    pg_hook.run(insert_query, parameters=record)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 418, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 473, in _run_command
    cur.execute(sql_statement, parameters)
psycopg2.errors.UndefinedColumn: column "TimeGetData" of relation "cybertrack_superapps_v_transfer" does not exist
LINE 20:         "TimeGetData"
                 ^

[2024-06-11T06:46:24.409+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=mssql_to_postgresql_13, task_id=load_to_postgresql, run_id=scheduled__2024-06-10T00:00:00+00:00, execution_date=20240610T000000, start_date=20240611T064624, end_date=20240611T064624
[2024-06-11T06:46:24.414+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 47 for task load_to_postgresql (column "TimeGetData" of relation "cybertrack_superapps_v_transfer" does not exist
LINE 20:         "TimeGetData"
                 ^
; 3366)
[2024-06-11T06:46:24.424+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-11T06:46:24.433+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-11T06:46:24.435+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
