[2024-06-11T08:07:51.379+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-11T08:07:51.402+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_ingest_cybertrack_superapps_v_billpayment.load_to_postgresql manual__2024-06-11T08:07:49.680035+00:00 [queued]>
[2024-06-11T08:07:51.407+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_ingest_cybertrack_superapps_v_billpayment.load_to_postgresql manual__2024-06-11T08:07:49.680035+00:00 [queued]>
[2024-06-11T08:07:51.407+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-11T08:07:51.414+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_to_postgresql> on 2024-06-11 08:07:49.680035+00:00
[2024-06-11T08:07:51.419+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=6022) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-11T08:07:51.419+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_ingest_cybertrack_superapps_v_billpayment', 'load_to_postgresql', 'manual__2024-06-11T08:07:49.680035+00:00', '--job-id', '108', '--raw', '--subdir', 'DAGS_FOLDER/dag_billpayment.py', '--cfg-path', '/tmp/tmpf9qlgdwx']
[2024-06-11T08:07:51.422+0000] {standard_task_runner.py:63} INFO - Started process 6023 to run task
[2024-06-11T08:07:51.422+0000] {standard_task_runner.py:91} INFO - Job 108: Subtask load_to_postgresql
[2024-06-11T08:07:51.448+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_ingest_cybertrack_superapps_v_billpayment.load_to_postgresql manual__2024-06-11T08:07:49.680035+00:00 [running]> on host 2e5c63130483
[2024-06-11T08:07:51.509+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_ingest_cybertrack_superapps_v_billpayment' AIRFLOW_CTX_TASK_ID='load_to_postgresql' AIRFLOW_CTX_EXECUTION_DATE='2024-06-11T08:07:49.680035+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-11T08:07:49.680035+00:00'
[2024-06-11T08:07:51.510+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-11T08:07:51.526+0000] {base.py:84} INFO - Using connection ID 'postgres_conn' for task execution.
[2024-06-11T08:07:51.531+0000] {sql.py:470} INFO - Running statement: 
    INSERT INTO new_schema_for_test.cybertrack_superapps_v_billpayment (
        "Id",
        "AccountID",
        "AccountName",
        "AccountType",
        "AccountStatus",
        "AccountCurrency",
        "TransactionID",
        "TransactionDatetime",
        "TransactionType",
        "TransactionSOFType",
        "TransactionAmount",
        "TransactionStatus",
        "TransactionMessage",
        "ProductName",
        "NoPelanggan",
        "AccountCIFNo",
        "AccountNIK",
        "AccountPhoneNo",
        "timegetdata"
    ) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
    , parameters: [1333806, 'd6da29c46ad5a021213d90014409de84', 'fbf107d14b4649f4ad4f7eee0f8d58a5', 'PAYROLL', 'ACTIVE', '360', 'BW2024061078062241', datetime.datetime(2024, 6, 10, 22, 46, 45, 190000), 'OVO', 'Nobu Payroll ****6362', 100000, 'Success', 'NULL', 'CY****A EL***A SA** SI****N', '081281120539', '230929120041000', 'NULL', '51864957a76b2b13ea13b071540038f8', '2024-06-11 15:07:50']
[2024-06-11T08:07:51.532+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-11T08:07:51.533+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_billpayment.py", line 66, in load_to_postgresql
    pg_hook.run(insert_query, parameters=record)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 418, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 473, in _run_command
    cur.execute(sql_statement, parameters)
psycopg2.errors.UndefinedTable: relation "new_schema_for_test.cybertrack_superapps_v_billpayment" does not exist
LINE 2:     INSERT INTO new_schema_for_test.cybertrack_superapps_v_b...
                        ^

[2024-06-11T08:07:51.540+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dag_ingest_cybertrack_superapps_v_billpayment, task_id=load_to_postgresql, run_id=manual__2024-06-11T08:07:49.680035+00:00, execution_date=20240611T080749, start_date=20240611T080751, end_date=20240611T080751
[2024-06-11T08:07:51.546+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 108 for task load_to_postgresql (relation "new_schema_for_test.cybertrack_superapps_v_billpayment" does not exist
LINE 2:     INSERT INTO new_schema_for_test.cybertrack_superapps_v_b...
                        ^
; 6023)
[2024-06-11T08:07:51.565+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-11T08:07:51.576+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-11T08:07:51.579+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
