[2024-06-10T09:45:47.459+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-10T09:45:47.479+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mssql_to_postgresql_01.extract_from_mssql scheduled__2024-06-09T00:00:00+00:00 [queued]>
[2024-06-10T09:45:47.483+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mssql_to_postgresql_01.extract_from_mssql scheduled__2024-06-09T00:00:00+00:00 [queued]>
[2024-06-10T09:45:47.483+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-10T09:45:47.490+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_from_mssql> on 2024-06-09 00:00:00+00:00
[2024-06-10T09:45:47.496+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'mssql_to_postgresql_01', 'extract_from_mssql', 'scheduled__2024-06-09T00:00:00+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/dag_testconnection.py', '--cfg-path', '/tmp/tmp2hxje924']
[2024-06-10T09:45:47.497+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1541) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-10T09:45:47.498+0000] {standard_task_runner.py:91} INFO - Job 19: Subtask extract_from_mssql
[2024-06-10T09:45:47.498+0000] {standard_task_runner.py:63} INFO - Started process 1542 to run task
[2024-06-10T09:45:47.525+0000] {task_command.py:426} INFO - Running <TaskInstance: mssql_to_postgresql_01.extract_from_mssql scheduled__2024-06-09T00:00:00+00:00 [running]> on host 5f414d64f7b6
[2024-06-10T09:45:47.565+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='mssql_to_postgresql_01' AIRFLOW_CTX_TASK_ID='extract_from_mssql' AIRFLOW_CTX_EXECUTION_DATE='2024-06-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-09T00:00:00+00:00'
[2024-06-10T09:45:47.565+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-10T09:45:47.577+0000] {base.py:84} INFO - Using connection ID 'sql_server_conn' for task execution.
[2024-06-10T09:45:56.627+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-10T09:45:56.632+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "src/pymssql/_pymssql.pyx", line 650, in pymssql._pymssql.connect
  File "src/pymssql/_mssql.pyx", line 2155, in pymssql._mssql.connect
  File "src/pymssql/_mssql.pyx", line 712, in pymssql._mssql.MSSQLConnection.__init__
  File "src/pymssql/_mssql.pyx", line 1881, in pymssql._mssql.maybe_raise_MSSQLDatabaseException
  File "src/pymssql/_mssql.pyx", line 1898, in pymssql._mssql.raise_MSSQLDatabaseException
pymssql._mssql.MSSQLDatabaseException: (20009, b'DB-Lib error message 20009, severity 9:\nUnable to connect: Adaptive Server is unavailable or does not exist (localhost)\nNet-Lib error during Connection refused (111)\nDB-Lib error message 20009, severity 9:\nUnable to connect: Adaptive Server is unavailable or does not exist (localhost)\nNet-Lib error during Connection refused (111)\n')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_testconnection.py", line 25, in extract_from_mssql
    records = mssql_hook.get_records(sql)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 283, in get_records
    return self.run(sql=sql, parameters=parameters, handler=fetch_all_handler)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 411, in run
    with closing(self.get_conn()) as conn:
                 ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/microsoft/mssql/hooks/mssql.py", line 110, in get_conn
    return pymssql.connect(
           ^^^^^^^^^^^^^^^^
  File "src/pymssql/_pymssql.pyx", line 659, in pymssql._pymssql.connect
pymssql.exceptions.OperationalError: (20009, b'DB-Lib error message 20009, severity 9:\nUnable to connect: Adaptive Server is unavailable or does not exist (localhost)\nNet-Lib error during Connection refused (111)\nDB-Lib error message 20009, severity 9:\nUnable to connect: Adaptive Server is unavailable or does not exist (localhost)\nNet-Lib error during Connection refused (111)\n')
[2024-06-10T09:45:56.661+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=mssql_to_postgresql_01, task_id=extract_from_mssql, run_id=scheduled__2024-06-09T00:00:00+00:00, execution_date=20240609T000000, start_date=20240610T094547, end_date=20240610T094556
[2024-06-10T09:45:56.674+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 19 for task extract_from_mssql ((20009, b'DB-Lib error message 20009, severity 9:\nUnable to connect: Adaptive Server is unavailable or does not exist (localhost)\nNet-Lib error during Connection refused (111)\nDB-Lib error message 20009, severity 9:\nUnable to connect: Adaptive Server is unavailable or does not exist (localhost)\nNet-Lib error during Connection refused (111)\n'); 1542)
[2024-06-10T09:45:56.692+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-10T09:45:56.713+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-10T09:45:56.715+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
