[2024-06-11T05:04:35.463+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-11T05:04:35.477+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mssql_to_postgresql_8.load_to_postgresql scheduled__2024-06-10T00:00:00+00:00 [queued]>
[2024-06-11T05:04:35.482+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mssql_to_postgresql_8.load_to_postgresql scheduled__2024-06-10T00:00:00+00:00 [queued]>
[2024-06-11T05:04:35.483+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-11T05:04:35.491+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_to_postgresql> on 2024-06-10 00:00:00+00:00
[2024-06-11T05:04:35.495+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'mssql_to_postgresql_8', 'load_to_postgresql', 'scheduled__2024-06-10T00:00:00+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/copy_file_transfer.py', '--cfg-path', '/tmp/tmpvx7ne_vi']
[2024-06-11T05:04:35.497+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1638) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-11T05:04:35.497+0000] {standard_task_runner.py:91} INFO - Job 36: Subtask load_to_postgresql
[2024-06-11T05:04:35.499+0000] {standard_task_runner.py:63} INFO - Started process 1640 to run task
[2024-06-11T05:04:35.523+0000] {task_command.py:426} INFO - Running <TaskInstance: mssql_to_postgresql_8.load_to_postgresql scheduled__2024-06-10T00:00:00+00:00 [running]> on host 2e5c63130483
[2024-06-11T05:04:35.561+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='mssql_to_postgresql_8' AIRFLOW_CTX_TASK_ID='load_to_postgresql' AIRFLOW_CTX_EXECUTION_DATE='2024-06-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-10T00:00:00+00:00'
[2024-06-11T05:04:35.562+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-11T05:04:35.577+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-11T05:04:35.578+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/copy_file_transfer.py", line 58, in load_to_postgresql
    timestamp_str = record[2].split('timestamp=')[1].split(',')[0]
                    ^^^^^^^^^^^^^^^
AttributeError: 'datetime.datetime' object has no attribute 'split'
[2024-06-11T05:04:35.583+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=mssql_to_postgresql_8, task_id=load_to_postgresql, run_id=scheduled__2024-06-10T00:00:00+00:00, execution_date=20240610T000000, start_date=20240611T050435, end_date=20240611T050435
[2024-06-11T05:04:35.587+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 36 for task load_to_postgresql ('datetime.datetime' object has no attribute 'split'; 1640)
[2024-06-11T05:04:35.599+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-11T05:04:35.609+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-11T05:04:35.610+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
