[2024-06-10T09:13:38.406+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-10T09:13:38.460+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_postgres_connection_manual_dag_5.test_postgres_connection_manual_task manual__2024-06-10T09:13:37.660710+00:00 [queued]>
[2024-06-10T09:13:38.472+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_postgres_connection_manual_dag_5.test_postgres_connection_manual_task manual__2024-06-10T09:13:37.660710+00:00 [queued]>
[2024-06-10T09:13:38.472+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-10T09:13:38.483+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): test_postgres_connection_manual_task> on 2024-06-10 09:13:37.660710+00:00
[2024-06-10T09:13:38.490+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'test_postgres_connection_manual_dag_5', 'test_postgres_connection_manual_task', 'manual__2024-06-10T09:13:37.660710+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/dag_testconnection.py', '--cfg-path', '/tmp/tmpvaxpyzzf']
[2024-06-10T09:13:38.492+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=804) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-10T09:13:38.492+0000] {standard_task_runner.py:91} INFO - Job 13: Subtask test_postgres_connection_manual_task
[2024-06-10T09:13:38.492+0000] {standard_task_runner.py:63} INFO - Started process 805 to run task
[2024-06-10T09:13:38.533+0000] {task_command.py:426} INFO - Running <TaskInstance: test_postgres_connection_manual_dag_5.test_postgres_connection_manual_task manual__2024-06-10T09:13:37.660710+00:00 [running]> on host 5f414d64f7b6
[2024-06-10T09:13:38.616+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='test_postgres_connection_manual_dag_5' AIRFLOW_CTX_TASK_ID='test_postgres_connection_manual_task' AIRFLOW_CTX_EXECUTION_DATE='2024-06-10T09:13:37.660710+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-10T09:13:37.660710+00:00'
[2024-06-10T09:13:38.617+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-10T09:13:38.627+0000] {logging_mixin.py:188} INFO - Koneksi gagal: connection to server at "localhost" (::1), port 5434 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5434 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
[2024-06-10T09:13:38.627+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-10T09:13:38.628+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-10T09:13:38.635+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=test_postgres_connection_manual_dag_5, task_id=test_postgres_connection_manual_task, run_id=manual__2024-06-10T09:13:37.660710+00:00, execution_date=20240610T091337, start_date=20240610T091338, end_date=20240610T091338
[2024-06-10T09:13:38.677+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-10T09:13:38.687+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-10T09:13:38.687+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
