[2024-06-11T07:49:01.615+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-11T07:49:01.629+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_ingest_cybertrack_superapps_v_customer_qris.load_to_postgresql manual__2024-06-11T07:48:59.837950+00:00 [queued]>
[2024-06-11T07:49:01.632+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_ingest_cybertrack_superapps_v_customer_qris.load_to_postgresql manual__2024-06-11T07:48:59.837950+00:00 [queued]>
[2024-06-11T07:49:01.633+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-11T07:49:01.638+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_to_postgresql> on 2024-06-11 07:48:59.837950+00:00
[2024-06-11T07:49:01.641+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=5364) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-11T07:49:01.642+0000] {standard_task_runner.py:63} INFO - Started process 5365 to run task
[2024-06-11T07:49:01.641+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_ingest_cybertrack_superapps_v_customer_qris', 'load_to_postgresql', 'manual__2024-06-11T07:48:59.837950+00:00', '--job-id', '101', '--raw', '--subdir', 'DAGS_FOLDER/dag_qris.py', '--cfg-path', '/tmp/tmpldm_gouo']
[2024-06-11T07:49:01.642+0000] {standard_task_runner.py:91} INFO - Job 101: Subtask load_to_postgresql
[2024-06-11T07:49:01.660+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_ingest_cybertrack_superapps_v_customer_qris.load_to_postgresql manual__2024-06-11T07:48:59.837950+00:00 [running]> on host 2e5c63130483
[2024-06-11T07:49:01.724+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_ingest_cybertrack_superapps_v_customer_qris' AIRFLOW_CTX_TASK_ID='load_to_postgresql' AIRFLOW_CTX_EXECUTION_DATE='2024-06-11T07:48:59.837950+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-11T07:48:59.837950+00:00'
[2024-06-11T07:49:01.724+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-11T07:49:01.743+0000] {base.py:84} INFO - Using connection ID 'postgres_conn' for task execution.
[2024-06-11T07:49:01.752+0000] {sql.py:470} INFO - Running statement: 
    INSERT INTO raw_data.cybertrack_superapps_v_customer_qris (
        "AccountID",
        "AccountName",
        "AccountType",
        "AccountStatus",
        "AccountCurrency",
        "TransactionID",
        "TransactionDatetime",
        "TransactionType",
        "TransactionSOFType",
        "TransactionAmount",
        "IssuerName",
        "MPANID",
        "MerchantName",
        "MerchantLongitude",
        "AccountCIFNo",
        "AccountPhoneNo",
        "AccountEmail",
        "TransactionStatus",
         "timegetdata"
    ) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
, parameters: [783554, '814b0a88fae4a41cb44a7a39cc79e5c3', '1b015885ae8c38cde668aea38d4cd868', 'SAVING', 'ACTIVE', '360', 'QR2024061078061734', datetime.datetime(2024, 6, 10, 21, 58, 21, 940000), 'QRIS', 'Nobu Savings ****4751', 50000, 'Nobu ePay', '936000110000246512', 'e7bdb97da6c05fd6d7c0be51baa5c8f5', 'BEKASI', '240610193626000', 'db6252bb58401e5c400c696fcf5a3f54', '8f0923fc26c84885ab9c26edc716860f', 'Success', '2024-06-11 14:49:00']
[2024-06-11T07:49:01.753+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-11T07:49:01.753+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_qris.py", line 66, in load_to_postgresql
    pg_hook.run(insert_query, parameters=record)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 418, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 473, in _run_command
    cur.execute(sql_statement, parameters)
TypeError: not all arguments converted during string formatting
[2024-06-11T07:49:01.760+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dag_ingest_cybertrack_superapps_v_customer_qris, task_id=load_to_postgresql, run_id=manual__2024-06-11T07:48:59.837950+00:00, execution_date=20240611T074859, start_date=20240611T074901, end_date=20240611T074901
[2024-06-11T07:49:01.766+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 101 for task load_to_postgresql (not all arguments converted during string formatting; 5365)
[2024-06-11T07:49:01.783+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-11T07:49:01.793+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-11T07:49:01.795+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
