[2024-06-11T07:22:18.196+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-11T07:22:18.213+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: copy_raw_data2.load_to_postgresql manual__2024-06-11T07:22:16.968539+00:00 [queued]>
[2024-06-11T07:22:18.217+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: copy_raw_data2.load_to_postgresql manual__2024-06-11T07:22:16.968539+00:00 [queued]>
[2024-06-11T07:22:18.217+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-11T07:22:18.223+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_to_postgresql> on 2024-06-11 07:22:16.968539+00:00
[2024-06-11T07:22:18.227+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=4647) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-11T07:22:18.228+0000] {standard_task_runner.py:63} INFO - Started process 4648 to run task
[2024-06-11T07:22:18.227+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'copy_raw_data2', 'load_to_postgresql', 'manual__2024-06-11T07:22:16.968539+00:00', '--job-id', '85', '--raw', '--subdir', 'DAGS_FOLDER/copy_file_transfer.py', '--cfg-path', '/tmp/tmp9y2zjdlx']
[2024-06-11T07:22:18.229+0000] {standard_task_runner.py:91} INFO - Job 85: Subtask load_to_postgresql
[2024-06-11T07:22:18.252+0000] {task_command.py:426} INFO - Running <TaskInstance: copy_raw_data2.load_to_postgresql manual__2024-06-11T07:22:16.968539+00:00 [running]> on host 2e5c63130483
[2024-06-11T07:22:18.294+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='copy_raw_data2' AIRFLOW_CTX_TASK_ID='load_to_postgresql' AIRFLOW_CTX_EXECUTION_DATE='2024-06-11T07:22:16.968539+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-11T07:22:16.968539+00:00'
[2024-06-11T07:22:18.295+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-11T07:22:18.322+0000] {base.py:84} INFO - Using connection ID 'postgres_conn' for task execution.
[2024-06-11T07:22:18.326+0000] {sql.py:470} INFO - Running statement: 
    INSERT INTO raw_data.cybertrack_superapps_v_transfer (
        "Id", 
        "TransactionID", 
        "TransactionDatetime", 
        "TransactionType", 
        "TransactionAmount", 
        "TransactionStatus", 
        "SourceAccountId", 
        "SourceAccountName", 
        "SourceAccountType", 
        "DestinationAccountId", 
        "DestinationAccountName", 
        "DestinationAccountBank", 
        "TransactionCategory", 
        "AccountCIFNo", 
        "AccountPhoneNo", 
        "AccountEmail", 
        "SourceAccountStatus",
        "timegetdata"
    ) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
    , parameters: [1023441, 'TB2024061078062253', datetime.datetime(2024, 6, 10, 22, 48, 38, 970000), 'TRF_BIFAST', 107500, 'Success', '619e5479cbe178e81b36ddc98b3018be', '5c9516baef42d316a891a276633e491d', 'SAVING', '693817191564', 'OKTAVIANUS DWI FIGO NAINGGOLAN', 'OCBC', 'TRF_BIFAST', '240603140111000', 'edd46da3a52880334c0f2795f5e5344f', '9ea5955fd9a9bb7621e5398b0459c9d5', 'ACTIVE', '2024-06-11 14:22:17']
[2024-06-11T07:22:18.328+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-11T07:22:18.329+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/copy_file_transfer.py", line 65, in load_to_postgresql
    pg_hook.run(insert_query, parameters=record)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 418, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 473, in _run_command
    cur.execute(sql_statement, parameters)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "cybertrack_superapps_v_transfer_pkey"
DETAIL:  Key ("Id")=(1023441) already exists.

[2024-06-11T07:22:18.333+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=copy_raw_data2, task_id=load_to_postgresql, run_id=manual__2024-06-11T07:22:16.968539+00:00, execution_date=20240611T072216, start_date=20240611T072218, end_date=20240611T072218
[2024-06-11T07:22:18.338+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 85 for task load_to_postgresql (duplicate key value violates unique constraint "cybertrack_superapps_v_transfer_pkey"
DETAIL:  Key ("Id")=(1023441) already exists.
; 4648)
[2024-06-11T07:22:18.368+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-11T07:22:18.379+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-11T07:22:18.380+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
