[2024-06-10T09:04:33.002+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-10T09:04:33.043+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_airflow_connection_dag.test_airflow_connection_task manual__2024-06-10T09:04:32.140255+00:00 [queued]>
[2024-06-10T09:04:33.049+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_airflow_connection_dag.test_airflow_connection_task manual__2024-06-10T09:04:32.140255+00:00 [queued]>
[2024-06-10T09:04:33.049+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-10T09:04:33.056+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): test_airflow_connection_task> on 2024-06-10 09:04:32.140255+00:00
[2024-06-10T09:04:33.066+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'test_***_connection_dag', 'test_***_connection_task', 'manual__2024-06-10T09:04:32.140255+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/dag_testconnection.py', '--cfg-path', '/tmp/tmp5gb0cznu']
[2024-06-10T09:04:33.072+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=587) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-10T09:04:33.072+0000] {standard_task_runner.py:91} INFO - Job 9: Subtask test_***_connection_task
[2024-06-10T09:04:33.073+0000] {standard_task_runner.py:63} INFO - Started process 588 to run task
[2024-06-10T09:04:33.100+0000] {task_command.py:426} INFO - Running <TaskInstance: test_airflow_connection_dag.test_airflow_connection_task manual__2024-06-10T09:04:32.140255+00:00 [running]> on host 5f414d64f7b6
[2024-06-10T09:04:33.147+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='test_***_connection_dag' AIRFLOW_CTX_TASK_ID='test_***_connection_task' AIRFLOW_CTX_EXECUTION_DATE='2024-06-10T09:04:32.140255+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-10T09:04:32.140255+00:00'
[2024-06-10T09:04:33.148+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-10T09:04:33.173+0000] {base.py:84} INFO - Using connection ID 'sql_server_conn' for task execution.
[2024-06-10T09:04:42.227+0000] {logging_mixin.py:188} INFO - Koneksi gagal: (20009, b'DB-Lib error message 20009, severity 9:\nUnable to connect: Adaptive Server is unavailable or does not exist (localhost)\nNet-Lib error during Connection refused (111)\nDB-Lib error message 20009, severity 9:\nUnable to connect: Adaptive Server is unavailable or does not exist (localhost)\nNet-Lib error during Connection refused (111)\n')
[2024-06-10T09:04:42.232+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-10T09:04:42.236+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-10T09:04:42.262+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=test_***_connection_dag, task_id=test_***_connection_task, run_id=manual__2024-06-10T09:04:32.140255+00:00, execution_date=20240610T090432, start_date=20240610T090433, end_date=20240610T090442
[2024-06-10T09:04:42.288+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-10T09:04:42.303+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-10T09:04:42.304+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
