[2024-06-10T09:07:40.528+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-10T09:07:40.547+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_sqlalchemy_connection_dag_1.test_sqlalchemy_connection_task manual__2024-06-10T09:07:39.231817+00:00 [queued]>
[2024-06-10T09:07:40.551+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_sqlalchemy_connection_dag_1.test_sqlalchemy_connection_task manual__2024-06-10T09:07:39.231817+00:00 [queued]>
[2024-06-10T09:07:40.551+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-10T09:07:40.557+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): test_sqlalchemy_connection_task> on 2024-06-10 09:07:39.231817+00:00
[2024-06-10T09:07:40.563+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=656) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-10T09:07:40.562+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'test_sqlalchemy_connection_dag_1', 'test_sqlalchemy_connection_task', 'manual__2024-06-10T09:07:39.231817+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/dag_testconnection.py', '--cfg-path', '/tmp/tmp8ir6n6fd']
[2024-06-10T09:07:40.564+0000] {standard_task_runner.py:63} INFO - Started process 657 to run task
[2024-06-10T09:07:40.564+0000] {standard_task_runner.py:91} INFO - Job 10: Subtask test_sqlalchemy_connection_task
[2024-06-10T09:07:40.591+0000] {task_command.py:426} INFO - Running <TaskInstance: test_sqlalchemy_connection_dag_1.test_sqlalchemy_connection_task manual__2024-06-10T09:07:39.231817+00:00 [running]> on host 5f414d64f7b6
[2024-06-10T09:07:40.638+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='test_sqlalchemy_connection_dag_1' AIRFLOW_CTX_TASK_ID='test_sqlalchemy_connection_task' AIRFLOW_CTX_EXECUTION_DATE='2024-06-10T09:07:39.231817+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-10T09:07:39.231817+00:00'
[2024-06-10T09:07:40.639+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-10T09:07:49.688+0000] {logging_mixin.py:188} INFO - Koneksi gagal: (pymssql.exceptions.OperationalError) (20009, b'DB-Lib error message 20009, severity 9:\nUnable to connect: Adaptive Server is unavailable or does not exist (localhost)\nNet-Lib error during Connection refused (111)\nDB-Lib error message 20009, severity 9:\nUnable to connect: Adaptive Server is unavailable or does not exist (localhost)\nNet-Lib error during Connection refused (111)\n')
(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2024-06-10T09:07:49.696+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-10T09:07:49.706+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-10T09:07:49.743+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=test_sqlalchemy_connection_dag_1, task_id=test_sqlalchemy_connection_task, run_id=manual__2024-06-10T09:07:39.231817+00:00, execution_date=20240610T090739, start_date=20240610T090740, end_date=20240610T090749
[2024-06-10T09:07:49.771+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-10T09:07:49.792+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-10T09:07:49.793+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
