[2024-06-11T05:04:36.570+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-11T05:04:36.583+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mssql_to_postgresql_8.load_to_postgresql manual__2024-06-11T05:04:34.741430+00:00 [queued]>
[2024-06-11T05:04:36.587+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mssql_to_postgresql_8.load_to_postgresql manual__2024-06-11T05:04:34.741430+00:00 [queued]>
[2024-06-11T05:04:36.588+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-11T05:04:36.592+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_to_postgresql> on 2024-06-11 05:04:34.741430+00:00
[2024-06-11T05:04:36.595+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'mssql_to_postgresql_8', 'load_to_postgresql', 'manual__2024-06-11T05:04:34.741430+00:00', '--job-id', '37', '--raw', '--subdir', 'DAGS_FOLDER/copy_file_transfer.py', '--cfg-path', '/tmp/tmpanhiboty']
[2024-06-11T05:04:36.596+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1641) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-11T05:04:36.597+0000] {standard_task_runner.py:91} INFO - Job 37: Subtask load_to_postgresql
[2024-06-11T05:04:36.597+0000] {standard_task_runner.py:63} INFO - Started process 1642 to run task
[2024-06-11T05:04:36.616+0000] {task_command.py:426} INFO - Running <TaskInstance: mssql_to_postgresql_8.load_to_postgresql manual__2024-06-11T05:04:34.741430+00:00 [running]> on host 2e5c63130483
[2024-06-11T05:04:36.646+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='mssql_to_postgresql_8' AIRFLOW_CTX_TASK_ID='load_to_postgresql' AIRFLOW_CTX_EXECUTION_DATE='2024-06-11T05:04:34.741430+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-11T05:04:34.741430+00:00'
[2024-06-11T05:04:36.647+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-11T05:04:36.659+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-11T05:04:36.659+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/copy_file_transfer.py", line 58, in load_to_postgresql
    timestamp_str = record[2].split('timestamp=')[1].split(',')[0]
                    ^^^^^^^^^^^^^^^
AttributeError: 'datetime.datetime' object has no attribute 'split'
[2024-06-11T05:04:36.663+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=mssql_to_postgresql_8, task_id=load_to_postgresql, run_id=manual__2024-06-11T05:04:34.741430+00:00, execution_date=20240611T050434, start_date=20240611T050436, end_date=20240611T050436
[2024-06-11T05:04:36.667+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 37 for task load_to_postgresql ('datetime.datetime' object has no attribute 'split'; 1642)
[2024-06-11T05:04:36.698+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-11T05:04:36.708+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-11T05:04:36.709+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
